### ISSUE TITLE
DaaLoadTest_daa1 sets -Djava.security.manager=allow while running jcmd with default JVM

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-systemtest#146]
See https://github.com/eclipse-openj9/openj9/issues/13477#issuecomment-1419436694

DaaLoadTest_daa1_special_5m_24 failed and the test framework tried to use `jcmd` from the default JVM to get diagnostics. The default JVM is jdk11, but the test has the following environment variable set which doesn't work with jdk11. 
`../system.mk:59: Environment variable JAVA_TOOL_OPTIONS is set to '-Djava.security.manager=allow'`

We could use `jcmd` from the JVM under test instead.

@llxia @Mesbah-Alam fyi

**Comment by Mesbah-Alam** [comment]
Yes, STF is using jcmd.exe from whatever Java is on [PATH](https://github.com/adoptium/STF/blob/master/stf.core/scripts/stf/Commands.pm#L946
): 

```
FIND_JAVA: foreach my $dir (split(/;/,$ENV{PATH})) {
			$java = catfile($dir, 'java.exe');
			$jcmd = catfile($dir, 'jcmd.exe');
			if (-e $java) {
				last FIND_JAVA;
			}
		}
```

Will update this to use jcmd.exe from JAVA_HOME.
