### ISSUE TITLE
jdk20 Mauve FAIL: gnu.testlet.java.lang.ThreadDeath.classInfo.isAnnotationPresent (number 5)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-systemtest#147]
The following test is failing on jdk20, I expect it's incompatible with this version.

Mauve
FAIL: gnu.testlet.java.lang.ThreadDeath.classInfo.isAnnotationPresent (number 5)

https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.system_aarch64_linux_Nightly/1/tapResults/

It also fails on an Adoptium build.
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/208/tapResults/

@llxia @Mesbah-Alam

**Comment by pshipton** [comment]
It also fails in MiniMix_5m testing.

**Comment by Mesbah-Alam** [comment]
We may simply exclude `gnu.testlet.java.lang.ThreadDeath.classInfo.isAnnotationPresent` from the test load for Mauve, as Mauve is used only as a stress test. I will create PR for the exclude.
